/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(4), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(4), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(5), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(6), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(6), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(6), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(6), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(6), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(6), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(6), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(6), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(6), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(6), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(6), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(7), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(7), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(7), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(8), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(8), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(8), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(9), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(9), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(9), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(9), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(10), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(10), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(11), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(11), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(11), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(11), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(11), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(11), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(11), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(11), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(11), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(11), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(12), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(12), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(13), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(13), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(14), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(14), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(15), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(15), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(15), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(15), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(16), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(16), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(16), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(16), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(16), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(16), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(17), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(17), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(18), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(18), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(19), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(19), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(19), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(19), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(19), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(20), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(20), list);
		    }
		    break;


                    case 78:
		    {
			ArrayList list = new78();
			push(goTo(21), list);
		    }
		    break;


                    case 79:
		    {
			ArrayList list = new79();
			push(goTo(22), list);
		    }
		    break;


                    case 80:
		    {
			ArrayList list = new80();
			push(goTo(22), list);
		    }
		    break;


                    case 81:
		    {
			ArrayList list = new81();
			push(goTo(23), list);
		    }
		    break;


                    case 82:
		    {
			ArrayList list = new82();
			push(goTo(23), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PGoal node1 = (PGoal) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PGoal pgoalNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pgoalNode1 = new AGoal(listNode2);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PGoal pgoalNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pgoalNode1 = new AGoal(listNode3);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAction pactionNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pactionNode1 = new AFunctionAction(pfunctionNode2);
        }
	nodeList.add(pactionNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAction pactionNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pactionNode1 = new AStatementAction(pstatementNode2);
        }
	nodeList.add(pactionNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        {
        }
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new AFunction(pidentifierNode2, listNode3, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PStatement pstatementNode5;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new AFunction(pidentifierNode2, listNode4, pstatementNode5);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PArgument pargumentNode1;
        pargumentNode1 = (PArgument)nodeArrayList1.get(0);
	if(pargumentNode1 != null)
	{
	  listNode2.add(pargumentNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PArgument pargumentNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pargumentNode2 = (PArgument)nodeArrayList3.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pargumentNode2 != null)
	{
	  listNode3.add(pargumentNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        }

        pargumentNode1 = new AArgument(pidentifierNode2, listNode3);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        PValue pvalueNode3;
        pvalueNode3 = (PValue)nodeArrayList2.get(0);
	if(pvalueNode3 != null)
	{
	  listNode4.add(pvalueNode3);
	}
        }

        pargumentNode1 = new AArgument(pidentifierNode2, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        pvalueNode1 = (PValue)nodeArrayList2.get(0);
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PIdentifier pidentifierNode3;
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pidentifierNode3 = (PIdentifier)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatement(pidentifierNode2, pidentifierNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PIdentifier pidentifierNode3;
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList3.get(0);
        pidentifierNode3 = (PIdentifier)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStatement(pidentifierNode2, pidentifierNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pstatementNode1 = new APrintStatement(listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pstatementNode1 = new APrintStatement(listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        POperationAssign poperationassignNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        poperationassignNode3 = (POperationAssign)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAssignStatement(pidentifierNode2, poperationassignNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        POperationAssign poperationassignNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        poperationassignNode3 = (POperationAssign)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AAssignStatement(pidentifierNode2, poperationassignNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AArrayAssignStatement(pidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new AArrayAssignStatement(pidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pstatementNode1 = new AAssertStatement(listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pstatementNode1 = new AAssertStatement(listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new AFunctionStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new AFunctionStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        POperationAssign poperationassignNode1;
        {

        poperationassignNode1 = new AAssignOperationAssign();
        }
	nodeList.add(poperationassignNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        POperationAssign poperationassignNode1;
        {

        poperationassignNode1 = new AMinusAssignOperationAssign();
        }
	nodeList.add(poperationassignNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        POperationAssign poperationassignNode1;
        {

        poperationassignNode1 = new ADivAssignOperationAssign();
        }
	nodeList.add(poperationassignNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAddExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMinusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADivExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AModExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new APowExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdExpression(pidentifierNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AArrayAccessExpression(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFuncCallExpression(pfunctioncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList5.get(0);

        pexpressionNode1 = new AOpenExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        pidentifierNode2 = (PIdentifier)nodeArrayList3.get(0);

        pexpressionNode1 = new ATypeExpression(pidentifierNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pexpressionNode1 = new AMaxExpression(listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pexpressionNode1 = new AMinExpression(listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new AParExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pexpressionNode1 = new AArrayExpression(listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode2.add(pexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PExpression pexpressionNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pexpressionNode2 != null)
	{
	  listNode3.add(pexpressionNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        POperationLogical poperationlogicalNode3;
        PComparison pcomparisonNode4;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        {

        poperationlogicalNode3 = new AOrOperationLogical();
        }
        pcomparisonNode4 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALogOpComparison(pcomparisonNode2, poperationlogicalNode3, pcomparisonNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        pcomparisonNode1 = (PComparison)nodeArrayList1.get(0);
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        POperationLogical poperationlogicalNode3;
        PComparison pcomparisonNode4;
        pcomparisonNode2 = (PComparison)nodeArrayList1.get(0);
        {

        poperationlogicalNode3 = new AAndOperationLogical();
        }
        pcomparisonNode4 = (PComparison)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALogOpComparison(pcomparisonNode2, poperationlogicalNode3, pcomparisonNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PComparison pcomparisonNode2;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);

        pcomparisonNode1 = new ANotComparison(pcomparisonNode2);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PComparisonSymbol pcomparisonsymbolNode3;
        PExpression pexpressionNode4;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pcomparisonsymbolNode3 = (PComparisonSymbol)nodeArrayList2.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ACompareComparison(pexpressionNode2, pcomparisonsymbolNode3, pexpressionNode4);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {

        pcomparisonNode1 = new ATrueComparison();
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {

        pcomparisonNode1 = new AFalseComparison();
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonSymbol pcomparisonsymbolNode1;
        {

        pcomparisonsymbolNode1 = new AGrtComparisonSymbol();
        }
	nodeList.add(pcomparisonsymbolNode1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonSymbol pcomparisonsymbolNode1;
        {

        pcomparisonsymbolNode1 = new ALessComparisonSymbol();
        }
	nodeList.add(pcomparisonsymbolNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonSymbol pcomparisonsymbolNode1;
        {

        pcomparisonsymbolNode1 = new AGrtEqComparisonSymbol();
        }
	nodeList.add(pcomparisonsymbolNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonSymbol pcomparisonsymbolNode1;
        {

        pcomparisonsymbolNode1 = new ALessEqComparisonSymbol();
        }
	nodeList.add(pcomparisonsymbolNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonSymbol pcomparisonsymbolNode1;
        {

        pcomparisonsymbolNode1 = new ANEqComparisonSymbol();
        }
	nodeList.add(pcomparisonsymbolNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparisonSymbol pcomparisonsymbolNode1;
        {

        pcomparisonsymbolNode1 = new AEqComparisonSymbol();
        }
	nodeList.add(pcomparisonsymbolNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        }

        pfunctioncallNode1 = new AFunctionCall(pidentifierNode2, listNode3);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pfunctioncallNode1 = new AFunctionCall(pidentifierNode2, listNode4);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode2.add(pexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        PExpression pexpressionNode1;
        TypedLinkedList listNode2 = new TypedLinkedList();
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
        listNode2 = (TypedLinkedList)nodeArrayList3.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode3.add(pexpressionNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        PIdentifier pidentifierNode2;
        PFunctionCall pfunctioncallNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pfunctioncallNode3 = (PFunctionCall)nodeArrayList3.get(0);

        pvalueNode1 = new AFunctionValue(pidentifierNode2, pfunctioncallNode3);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        Object nullNode2 = null;
        TNumber tnumberNode3;
        tnumberNode3 = (TNumber)nodeArrayList1.get(0);

        pvalueNode1 = new ANumberValue(null, tnumberNode3);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TMinus tminusNode2;
        TNumber tnumberNode3;
        tminusNode2 = (TMinus)nodeArrayList1.get(0);
        tnumberNode3 = (TNumber)nodeArrayList2.get(0);

        pvalueNode1 = new ANumberValue(tminusNode2, tnumberNode3);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {

        pvalueNode1 = new ANoneValue();
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        PValue pvalueNode1;
        PValue pvalueNode2;
        pvalueNode1 = (PValue)nodeArrayList1.get(0);
        pvalueNode2 = (PValue)nodeArrayList3.get(0);
	if(pvalueNode1 != null)
	{
	  listNode3.add(pvalueNode1);
	}
	if(pvalueNode2 != null)
	{
	  listNode3.add(pvalueNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PValue pvalueNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pvalueNode2 = (PValue)nodeArrayList3.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pvalueNode2 != null)
	{
	  listNode3.add(pvalueNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new78()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PIdentifier pidentifierNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pidentifierNode1 = new AIdentifier(tidNode2);
        }
	nodeList.add(pidentifierNode1);
        return nodeList;
    }



    ArrayList new79()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PAction pactionNode1;
        pactionNode1 = (PAction)nodeArrayList1.get(0);
	if(pactionNode1 != null)
	{
	  listNode2.add(pactionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new80()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PAction pactionNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pactionNode2 = (PAction)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pactionNode2 != null)
	{
	  listNode3.add(pactionNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new81()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new82()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {3, SHIFT, 2}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 81}, },
			{{-1, ERROR, 2}, {44, SHIFT, 9}, },
			{{-1, ERROR, 3}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {25, SHIFT, 24}, {26, SHIFT, 25}, {27, SHIFT, 26}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 4}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {25, SHIFT, 24}, {26, SHIFT, 25}, {27, SHIFT, 26}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 5}, {44, SHIFT, 9}, },
			{{-1, ERROR, 6}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 7}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 8}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 78}, },
			{{-1, ERROR, 10}, {45, ACCEPT, -1}, },
			{{-1, REDUCE, 79}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 15}, {11, SHIFT, 48}, {13, SHIFT, 49}, {19, SHIFT, 50}, {20, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {3, SHIFT, 2}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 17}, {0, SHIFT, 55}, {35, SHIFT, 56}, {36, SHIFT, 57}, {37, SHIFT, 58}, {38, SHIFT, 59}, {39, SHIFT, 60}, {41, SHIFT, 61}, {44, SHIFT, 9}, },
			{{-1, ERROR, 18}, {11, SHIFT, 64}, },
			{{-1, REDUCE, 72}, },
			{{-1, REDUCE, 74}, },
			{{-1, ERROR, 21}, {1, SHIFT, 65}, },
			{{-1, ERROR, 22}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 23}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 60}, },
			{{-1, ERROR, 26}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {25, SHIFT, 24}, {26, SHIFT, 25}, {27, SHIFT, 26}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 27}, {11, SHIFT, 70}, },
			{{-1, ERROR, 28}, {11, SHIFT, 71}, },
			{{-1, ERROR, 29}, {11, SHIFT, 72}, },
			{{-1, ERROR, 30}, {11, SHIFT, 73}, },
			{{-1, REDUCE, 75}, },
			{{-1, ERROR, 32}, {4, SHIFT, 74}, {5, SHIFT, 75}, {17, SHIFT, 76}, {18, SHIFT, 77}, {21, SHIFT, 78}, {22, SHIFT, 79}, {23, SHIFT, 80}, {24, SHIFT, 81}, },
			{{-1, REDUCE, 32}, {7, SHIFT, 83}, {8, SHIFT, 84}, {9, SHIFT, 85}, },
			{{-1, REDUCE, 35}, {6, SHIFT, 86}, },
			{{-1, REDUCE, 39}, },
			{{-1, ERROR, 36}, {16, SHIFT, 87}, {28, SHIFT, 88}, {29, SHIFT, 89}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 41}, {11, SHIFT, 48}, {13, SHIFT, 90}, {40, SHIFT, 91}, },
			{{-1, ERROR, 42}, {16, SHIFT, 92}, {28, SHIFT, 88}, {29, SHIFT, 89}, },
			{{-1, ERROR, 43}, {42, SHIFT, 93}, },
			{{-1, REDUCE, 51}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
			{{-1, REDUCE, 19}, {15, SHIFT, 94}, },
			{{-1, REDUCE, 17}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
			{{-1, REDUCE, 25}, {15, SHIFT, 94}, },
			{{-1, ERROR, 48}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {12, SHIFT, 95}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 49}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 53}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 80}, },
			{{-1, REDUCE, 82}, },
			{{-1, ERROR, 56}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {25, SHIFT, 24}, {26, SHIFT, 25}, {27, SHIFT, 26}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 57}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {25, SHIFT, 24}, {26, SHIFT, 25}, {27, SHIFT, 26}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 58}, {44, SHIFT, 9}, },
			{{-1, ERROR, 59}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 60}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 61}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 63}, {11, SHIFT, 48}, {13, SHIFT, 105}, {19, SHIFT, 50}, {20, SHIFT, 51}, {30, SHIFT, 52}, },
			{{-1, ERROR, 64}, {12, SHIFT, 107}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 73}, },
			{{-1, ERROR, 66}, {4, SHIFT, 74}, {5, SHIFT, 75}, {12, SHIFT, 111}, },
			{{-1, REDUCE, 69}, {4, SHIFT, 74}, {5, SHIFT, 75}, {15, SHIFT, 112}, },
			{{-1, ERROR, 68}, {14, SHIFT, 113}, },
			{{-1, REDUCE, 57}, },
			{{-1, ERROR, 70}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 71}, {44, SHIFT, 9}, },
			{{-1, ERROR, 72}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 73}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 74}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 75}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 66}, },
			{{-1, REDUCE, 65}, },
			{{-1, REDUCE, 62}, },
			{{-1, REDUCE, 61}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 63}, },
			{{-1, ERROR, 82}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 83}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 84}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 85}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 86}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 87}, {0, SHIFT, 1}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 88}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {25, SHIFT, 24}, {26, SHIFT, 25}, {27, SHIFT, 26}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 89}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {25, SHIFT, 24}, {26, SHIFT, 25}, {27, SHIFT, 26}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 90}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 91}, {44, SHIFT, 9}, },
			{{-1, ERROR, 92}, {0, SHIFT, 1}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 93}, {44, SHIFT, 9}, },
			{{-1, ERROR, 94}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 67}, },
			{{-1, ERROR, 96}, {12, SHIFT, 136}, },
			{{-1, ERROR, 97}, {4, SHIFT, 74}, {5, SHIFT, 75}, {14, SHIFT, 137}, },
			{{-1, REDUCE, 21}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
			{{-1, ERROR, 99}, {16, SHIFT, 138}, {28, SHIFT, 88}, {29, SHIFT, 89}, },
			{{-1, ERROR, 100}, {16, SHIFT, 139}, {28, SHIFT, 88}, {29, SHIFT, 89}, },
			{{-1, ERROR, 101}, {42, SHIFT, 140}, },
			{{-1, REDUCE, 20}, {15, SHIFT, 94}, },
			{{-1, REDUCE, 18}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
			{{-1, REDUCE, 26}, {15, SHIFT, 94}, },
			{{-1, ERROR, 105}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 106}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, ERROR, 107}, {16, SHIFT, 143}, },
			{{-1, ERROR, 108}, {12, SHIFT, 144}, {15, SHIFT, 145}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 8}, {30, SHIFT, 146}, },
			{{-1, REDUCE, 49}, },
			{{-1, ERROR, 112}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 114}, {4, SHIFT, 74}, {5, SHIFT, 75}, {15, SHIFT, 149}, },
			{{-1, ERROR, 115}, {12, SHIFT, 150}, },
			{{-1, ERROR, 116}, {15, SHIFT, 151}, },
			{{-1, ERROR, 117}, {12, SHIFT, 152}, {15, SHIFT, 153}, },
			{{-1, ERROR, 118}, {40, SHIFT, 91}, },
			{{-1, ERROR, 119}, {12, SHIFT, 154}, {15, SHIFT, 153}, },
			{{-1, REDUCE, 33}, {7, SHIFT, 83}, {8, SHIFT, 84}, {9, SHIFT, 85}, },
			{{-1, REDUCE, 34}, {7, SHIFT, 83}, {8, SHIFT, 84}, {9, SHIFT, 85}, },
			{{-1, REDUCE, 58}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
			{{-1, REDUCE, 36}, {6, SHIFT, 86}, },
			{{-1, REDUCE, 37}, {6, SHIFT, 86}, },
			{{-1, REDUCE, 38}, {6, SHIFT, 86}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 130}, {4, SHIFT, 74}, {5, SHIFT, 75}, {14, SHIFT, 155}, },
			{{-1, REDUCE, 71}, },
			{{-1, ERROR, 132}, {11, SHIFT, 48}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 134}, {16, SHIFT, 156}, },
			{{-1, REDUCE, 52}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 137}, {30, SHIFT, 157}, },
			{{-1, ERROR, 138}, {0, SHIFT, 1}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 139}, {0, SHIFT, 1}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 140}, {44, SHIFT, 9}, },
			{{-1, ERROR, 141}, {4, SHIFT, 74}, {5, SHIFT, 75}, {14, SHIFT, 161}, },
			{{-1, REDUCE, 22}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
			{{-1, ERROR, 143}, {0, SHIFT, 1}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 144}, {16, SHIFT, 163}, },
			{{-1, ERROR, 145}, {44, SHIFT, 9}, },
			{{-1, ERROR, 146}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 70}, },
			{{-1, ERROR, 149}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 46}, },
			{{-1, ERROR, 151}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 47}, },
			{{-1, ERROR, 153}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 42}, },
			{{-1, ERROR, 156}, {0, SHIFT, 1}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 157}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 160}, {16, SHIFT, 171}, },
			{{-1, ERROR, 161}, {30, SHIFT, 172}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 163}, {0, SHIFT, 1}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 10}, },
			{{-1, ERROR, 166}, {4, SHIFT, 74}, {5, SHIFT, 75}, {12, SHIFT, 174}, },
			{{-1, REDUCE, 76}, },
			{{-1, REDUCE, 77}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 23}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
			{{-1, ERROR, 171}, {0, SHIFT, 1}, {35, SHIFT, 3}, {36, SHIFT, 4}, {37, SHIFT, 5}, {38, SHIFT, 6}, {39, SHIFT, 7}, {41, SHIFT, 8}, {44, SHIFT, 9}, },
			{{-1, ERROR, 172}, {1, SHIFT, 19}, {2, SHIFT, 20}, {5, SHIFT, 21}, {11, SHIFT, 22}, {13, SHIFT, 23}, {31, SHIFT, 27}, {32, SHIFT, 28}, {33, SHIFT, 29}, {34, SHIFT, 30}, {43, SHIFT, 31}, {44, SHIFT, 9}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 24}, {4, SHIFT, 74}, {5, SHIFT, 75}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 10}, },
			{{-1, 11}, {16, 54}, },
			{{-1, 12}, },
			{{-1, 108}, },
			{{-1, 109}, {145, 164}, },
			{{-1, 147}, },
			{{-1, 13}, {87, 127}, {92, 133}, {138, 158}, {139, 159}, {143, 162}, {156, 169}, {163, 173}, {171, 175}, },
			{{-1, 53}, {63, 106}, },
			{{-1, 32}, {6, 44}, {7, 46}, {8, 44}, {22, 66}, {23, 67}, {48, 67}, {49, 97}, {53, 98}, {59, 44}, {60, 103}, {61, 44}, {70, 114}, {82, 122}, {90, 130}, {94, 135}, {105, 141}, {106, 142}, {112, 67}, {149, 166}, {157, 170}, {172, 176}, },
			{{-1, 33}, {74, 120}, {75, 121}, },
			{{-1, 34}, {83, 123}, {84, 124}, {85, 125}, },
			{{-1, 35}, {86, 126}, },
			{{-1, 45}, {8, 47}, {59, 102}, {61, 104}, },
			{{-1, 36}, {4, 42}, {56, 99}, {57, 100}, },
			{{-1, 37}, },
			{{-1, 38}, {26, 69}, {88, 128}, {89, 129}, },
			{{-1, 82}, },
			{{-1, 39}, {0, 14}, {16, 14}, {17, 62}, {87, 14}, {91, 131}, {92, 14}, {138, 14}, {139, 14}, {143, 14}, {156, 14}, {163, 14}, {171, 14}, },
			{{-1, 68}, {48, 96}, {112, 148}, },
			{{-1, 40}, {72, 116}, {73, 116}, {146, 165}, {151, 167}, {153, 168}, },
			{{-1, 117}, {73, 119}, },
			{{-1, 41}, {0, 15}, {2, 18}, {5, 43}, {16, 15}, {17, 63}, {58, 101}, {64, 110}, {71, 115}, {72, 118}, {73, 118}, {87, 15}, {91, 132}, {92, 15}, {93, 134}, {138, 15}, {139, 15}, {140, 160}, {143, 15}, {145, 110}, {146, 118}, {151, 118}, {153, 118}, {156, 15}, {163, 15}, {171, 15}, },
			{{-1, 16}, },
			{{-1, 17}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'def', 'if', 'while', 'for', 'print', 'return', 'assert', id, EOF",
			"expecting: tab, 'if', 'while', 'for', 'print', 'return', 'assert', id",
			"expecting: id",
			"expecting: number, string, '-', '(', '[', 'true', 'false', 'not', 'open', 'type', 'max', 'min', 'None', id",
			"expecting: number, string, '-', '(', '[', 'open', 'type', 'max', 'min', 'None', id",
			"expecting: tab, 'def', '+', '-', '**', '*', '/', '%', '(', ')', '[', ']', ',', ':', '==', '!=', '-=', '/=', '<', '>', '<=', '>=', 'and', 'or', '=', 'if', 'while', 'for', 'print', 'return', '.', 'assert', 'in', id, EOF",
			"expecting: EOF",
			"expecting: '(', '[', '-=', '/=', '='",
			"expecting: '('",
			"expecting: tab, 'def', '+', '-', '**', '*', '/', '%', ')', ']', ',', ':', '==', '!=', '<', '>', '<=', '>=', 'and', 'or', 'if', 'while', 'for', 'print', 'return', 'assert', id, EOF",
			"expecting: number",
			"expecting: ':', 'and', 'or'",
			"expecting: '+', '-', '==', '!=', '<', '>', '<=', '>='",
			"expecting: tab, 'def', '+', '-', '*', '/', '%', ')', ']', ',', ':', '==', '!=', '<', '>', '<=', '>=', 'and', 'or', 'if', 'while', 'for', 'print', 'return', 'assert', id, EOF",
			"expecting: tab, 'def', '+', '-', '**', '*', '/', '%', '(', ')', '[', ']', ',', ':', '==', '!=', '<', '>', '<=', '>=', 'and', 'or', 'if', 'while', 'for', 'print', 'return', '.', 'assert', id, EOF",
			"expecting: 'in'",
			"expecting: tab, 'def', '+', '-', ',', 'if', 'while', 'for', 'print', 'return', 'assert', id, EOF",
			"expecting: tab, 'def', ',', 'if', 'while', 'for', 'print', 'return', 'assert', id, EOF",
			"expecting: tab, 'def', '+', '-', 'if', 'while', 'for', 'print', 'return', 'assert', id, EOF",
			"expecting: number, string, '-', '(', ')', '[', 'open', 'type', 'max', 'min', 'None', id",
			"expecting: ')', id",
			"expecting: '+', '-', ')'",
			"expecting: '+', '-', ')', ']', ','",
			"expecting: ']'",
			"expecting: number, string, '-', 'None', id",
			"expecting: ')'",
			"expecting: '+', '-', ']'",
			"expecting: ':'",
			"expecting: ')', ','",
			"expecting: ')', ',', '='",
			"expecting: '+', '-', ','",
			"expecting: ','",
			"expecting: '.'",
			"expecting: '+', '-', ':', 'and', 'or'",
			"expecting: '='",
			"expecting: ')', ']'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 2, 4, 4, 4, 5, 6, 0, 0, 0, 0, 7, 0, 1, 8, 9, 9, 10, 4, 4, 11, 11, 3, 8, 8, 8, 8, 9, 12, 13, 9, 9, 11, 11, 11, 9, 9, 14, 11, 15, 16, 17, 18, 17, 19, 4, 4, 4, 4, 4, 0, 1, 3, 3, 2, 4, 4, 4, 0, 7, 20, 9, 21, 22, 23, 11, 4, 2, 24, 24, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 3, 3, 4, 2, 1, 2, 4, 9, 25, 26, 18, 11, 11, 15, 17, 18, 17, 4, 4, 27, 28, 28, 29, 9, 4, 9, 30, 25, 31, 28, 32, 28, 13, 13, 33, 9, 9, 9, 9, 0, 11, 11, 26, 9, 8, 0, 27, 16, 9, 34, 1, 1, 2, 26, 18, 1, 27, 2, 24, 28, 35, 4, 9, 24, 9, 24, 9, 9, 1, 4, 0, 0, 27, 34, 0, 1, 28, 28, 21, 28, 28, 0, 18, 1, 4, 0, 9, 0, 18, 
        };*/
}
