/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAssignStatement extends PStatement
{
    private TIdentifier _identifier_;
    private POperationAssign _operationAssign_;
    private PExpression _expression_;

    public AAssignStatement()
    {
    }

    public AAssignStatement(
        TIdentifier _identifier_,
        POperationAssign _operationAssign_,
        PExpression _expression_)
    {
        setIdentifier(_identifier_);

        setOperationAssign(_operationAssign_);

        setExpression(_expression_);

    }
    public Object clone()
    {
        return new AAssignStatement(
            (TIdentifier) cloneNode(_identifier_),
            (POperationAssign) cloneNode(_operationAssign_),
            (PExpression) cloneNode(_expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStatement(this);
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public POperationAssign getOperationAssign()
    {
        return _operationAssign_;
    }

    public void setOperationAssign(POperationAssign node)
    {
        if(_operationAssign_ != null)
        {
            _operationAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _operationAssign_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_operationAssign_)
            + toString(_expression_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_operationAssign_ == child)
        {
            _operationAssign_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_operationAssign_ == oldChild)
        {
            setOperationAssign((POperationAssign) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

    }
}
