/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFunction extends PFunction
{
    private TIdentifier _identifier_;
    private final LinkedList _argument_ = new TypedLinkedList(new Argument_Cast());
    private PStatement _statement_;

    public AFunction()
    {
    }

    public AFunction(
        TIdentifier _identifier_,
        List _argument_,
        PStatement _statement_)
    {
        setIdentifier(_identifier_);

        {
            this._argument_.clear();
            this._argument_.addAll(_argument_);
        }

        setStatement(_statement_);

    }
    public Object clone()
    {
        return new AFunction(
            (TIdentifier) cloneNode(_identifier_),
            cloneList(_argument_),
            (PStatement) cloneNode(_statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunction(this);
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public LinkedList getArgument()
    {
        return _argument_;
    }

    public void setArgument(List list)
    {
        _argument_.clear();
        _argument_.addAll(list);
    }

    public PStatement getStatement()
    {
        return _statement_;
    }

    public void setStatement(PStatement node)
    {
        if(_statement_ != null)
        {
            _statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _statement_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_argument_)
            + toString(_statement_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_argument_.remove(child))
        {
            return;
        }

        if(_statement_ == child)
        {
            _statement_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator i = _argument_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

    }

    private class Argument_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PArgument node = (PArgument) o;

            if((node.parent() != null) &&
                (node.parent() != AFunction.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFunction.this))
            {
                node.parent(AFunction.this);
            }

            return node;
        }
    }
}
