/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDivEqual extends Token
{
    public TDivEqual()
    {
        super.setText("/=");
    }

    public TDivEqual(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDivEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDivEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDivEqual text.");
    }
}
