/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TGreater extends Token
{
    public TGreater()
    {
        super.setText(">");
    }

    public TGreater(int line, int pos)
    {
        super.setText(">");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGreater(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGreater(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGreater text.");
    }
}
