/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLessEqual extends Token
{
    public TLessEqual()
    {
        super.setText("<=");
    }

    public TLessEqual(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLessEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLessEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLessEqual text.");
    }
}
