/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TMinusEqual extends Token
{
    public TMinusEqual()
    {
        super.setText("-=");
    }

    public TMinusEqual(int line, int pos)
    {
        super.setText("-=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMinusEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMinusEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMinusEqual text.");
    }
}
