/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TNotEqual extends Token
{
    public TNotEqual()
    {
        super.setText("!=");
    }

    public TNotEqual(int line, int pos)
    {
        super.setText("!=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TNotEqual(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNotEqual(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TNotEqual text.");
    }
}
